// ========================================
// TaskItem.cs
// Core data model for tasks and settings
// 
// Purpose:
// - TaskItem: Represents a single task with energy cost, deadline, status
// - AppSetting: Key-value store for app configuration (budget, reset time)
// - Validation rules for task properties
// 
// Database Mapping:
// - TaskItem → Tasks table (primary entity)
// - AppSetting → Settings table (configuration)
// 
// Validation Rules:
// - Title: Required, max 100 characters
// - EnergyCost: Required, range 5-100 points
// - Category: Required, default "Personal"
// - Status: Enum (Backlog, Active, Completed), default Backlog
// - CreatedAt: Auto-set on creation
// - CompletedAt: Auto-set when status → Completed
// ========================================

using System;
using System.ComponentModel.DataAnnotations;

namespace BatteryWorkflowMVC.Models
{
    /// <summary>
    /// Represents a task in the energy-aware workflow system
    /// Maps to Tasks database table
    /// </summary>
    public class TaskItem
    {
        // Primary key - auto-generated by database
        public int Id { get; set; }

        // Task name/description (required, max 100 chars)
        [Required(ErrorMessage = "Task title is required")]
        [StringLength(100, ErrorMessage = "Title cannot exceed 100 characters")]
        public string Title { get; set; } = string.Empty;

        // Energy cost in points (5-100 range)
        // Used to calculate daily energy budget consumption
        [Required(ErrorMessage = "Energy cost is required")]
        [Range(5, 100, ErrorMessage = "Energy cost must be between 5 and 100")]
        public int EnergyCost { get; set; }

        // Task category for organization and filtering
        [Required]
        [StringLength(50)]
        public string Category { get; set; } = "Personal";

        // Optional deadline for time-sensitive tasks
        public DateTime? Deadline { get; set; }

        // Optional detailed description
        [StringLength(500, ErrorMessage = "Description cannot exceed 500 characters")]
        public string? Description { get; set; }

        // Current workflow status (Backlog → Active → Completed)
        public TaskStatus Status { get; set; } = TaskStatus.Backlog;

        // Timestamp when task was created (auto-set)
        public DateTime CreatedAt { get; set; } = DateTime.Now;

        // Timestamp when task was completed (set when Status → Completed)
        public DateTime? CompletedAt { get; set; }
    }
    
    /// <summary>
    /// Key-value configuration store for app settings
    /// Maps to Settings database table
    /// Used for: DailyBudget, ResetTime
    /// </summary>
    public class AppSetting
    {
        // Primary key - auto-generated by database
        public int Id { get; set; }
        
        // Setting identifier (e.g., "DailyBudget", "ResetTime")
        [Required]
        [StringLength(50)]
        public string Key { get; set; } = string.Empty;
        
        // Setting value as string (parsed based on Key)
        [Required]
        [StringLength(200)]
        public string Value { get; set; } = string.Empty;
    }
}